### PR TITLE
Added sponsor & FAQ

### PR DESCRIPTION
**Pull request by bintay**
Many changes were lost for inexplicable reasons so animations were simplified to get it shipped faster.

Still needs 
- content
  - slider.json for resources/mentorship, etc
  - hacker's guide with FAQ and other info
- headshots of the team (will go in the grass slide like at the botton of https://hackthenorth.com/)
- change mailing list button to register now button

y
x
image

### CODE REVIEW

**Comment by bintay** [comment]
maybe make sponsor logos smaller

**Comment by Jeongwoo55** [comment]
Looks great overall!
Maybe speeding up the first animation and changing the text buttons to hover?
Schedule also needs a place. It can probably be a simple table but [this would be pretty cool](https://www.losaltoshacks.com/#schedule) though it is a bit hard to use

**Comment by Jeongwoo55** [comment]
> 
> 
> maybe make sponsor logos smaller

Not a bad idea since there might be more logos we add
Edit: Probably small enough to show all logos at once

**Comment by bintay** [comment]
> Schedule also needs a place. It can probably be a simple table but this would be pretty cool though it is a bit hard to use

Sounds like something for the hacker guide / live site

**Comment by Jeongwoo55** [comment]
> 
>     * change mailing list button to register now button
>

Also, include a [volunteer/mentor](https://hacktams.org/volunteer) button as well

**Comment by Jeongwoo55** [comment]
Maybe add an indication to scroll down. A simple arrow or text.
Also, add some sort of indication next to the text section next to the earth to show that it is supposed to change. I initially thought it was a bug.

**Comment by danielzting** [comment]
The preview is completely broken on mobile. I am clueless at web dev so I dunno exactly why, sorry :( But I did do a git bisect and everything broke on 50c6e180bf36109b493fb030c74dca54a5feec23, if that's helpful in tracking down the regression

**Pull request merged**
